### PR TITLE
added items with frost resistance

### PR DESCRIPTION
**Pull request by oeph**

### CODE REVIEW

**Comment by oeph** [comment]
this currently contains all the items that are available, so also classic and tbc items. should i remove all non wotlk-only items?

**Comment by LasterOfDesaster** [comment]
I will ask Shariva if he prefers to include classic and tbc fr items. I'll let you know

**Comment by oeph** [comment]
I talked to shariva. will keep all of the items and also add the rarity

**Comment by oeph** [comment]
I removed the name of the items and added the rarity. I also added an wotlk only item list if this may be favoured

**Comment by LasterOfDesaster** [comment]
Seems good 👍

**Comment by Arastrus** [comment]
List is missing a lot of items, reason unknown. PMed about it. Currently it's unuseable.

**Comment by oeph** [comment]
@Arastrus fixed with #4

**Pull request merged**
